max_steps: 1000
seed: 7878

world:
  size: 12
  start:
    x: 0
    y: 0
  end:
    x: 11
    y: 11
  traps:
    type: 'fixed'
    dist:
      - x: 0
        y: 3
      - x: 1
        y: 3
      - x: 2
        y: 3
      - x: 3
        y: 3
      - x: 4
        y: 3
      - x: 5
        y: 3
      - x: 6
        y: 3
      - x: 7
        y: 3
      
      - x: 4
        y: 7
      - x: 5
        y: 7
      - x: 6
        y: 7
      - x: 7
        y: 7
      - x: 8
        y: 7
      - x: 9
        y: 7
      - x: 10
        y: 7
      - x: 11
        y: 7

agent:
  type: 'sarsa'
  discount: 1.0
  obey_factor: 0.9
  learning_rate: 0.5

