\LoadClass[a4paper, 11pt]{article}

\RequirePackage{hyperref}
\RequirePackage{fullpage}
\RequirePackage{enumitem}
\RequirePackage{graphicx}
\RequirePackage{glossaries}
\numberwithin{equation}{section}

\RequirePackage{algorithm}
\RequirePackage{algorithmic}

\RequirePackage{concmath}
\RequirePackage[T1]{fontenc}
\RequirePackage[french]{babel}
\RequirePackage{amsmath}
\RequirePackage{amssymb,mathtools}
\RequirePackage{bm}
\RequirePackage{bbm}

\renewcommand{\algorithmicrequire}{\textsc{Entrée :}}
\renewcommand{\algorithmicensure}{\textsc{Sortie :}}
\renewcommand{\algorithmicif}{\textsc{Si}}
\renewcommand{\algorithmicelse}{\textsc{Sinon}}
\renewcommand{\algorithmicelsif}{\textsc{Sinon si}}
\renewcommand{\algorithmicrepeat}{\textsc{Faire}}
\renewcommand{\algorithmicuntil}{\textsc{Tant que}}
\renewcommand{\algorithmicdo}{\textsc{Faire}}
\renewcommand{\algorithmicthen}{\textsc{Alors}}
\renewcommand{\algorithmicwhile}{\textsc{Tant que}}
\renewcommand{\algorithmicfor}{\textsc{Pour}}
\renewcommand{\algorithmicend}{\textsc{Fin}}
\renewcommand{\algorithmicand}{\textsc{Et}}
\renewcommand{\algorithmicor}{\textsc{Ou}}
\renewcommand{\algorithmicxor}{\textsc{Exclusif ou}}
\renewcommand{\algorithmicnot}{\textsc{Non}}
\renewcommand{\algorithmictrue}{\textsc{Vrai}}
\renewcommand{\algorithmicfalse}{\textsc{Faux}}
\renewcommand{\algorithmicreturn}{\textsc{Retourner}}
\renewcommand{\algorithmiccomment}[1]{\texttt{\#} #1}
\renewcommand{\algorithmicto}{à}

