\LoadClass[a4paper, 11pt]{article}

\RequirePackage{hyperref}
\RequirePackage{fullpage}
\RequirePackage{enumerate}
\RequirePackage{graphicx}
\RequirePackage{glossaries}
\numberwithin{equation}{section}

\RequirePackage{algorithm}
\RequirePackage{algorithmic}

\RequirePackage{concmath}
\RequirePackage[T1]{fontenc}
\RequirePackage[french]{babel}
\RequirePackage{amsmath}
\RequirePackage{amssymb,mathtools}
\RequirePackage{bm}
\RequirePackage{bbm}

\renewcommand{\algorithmicrequire}{\textsc{Input:}}
\renewcommand{\algorithmicensure}{\textsc{Output:}}
\renewcommand{\algorithmicif}{\textsc{If}}
\renewcommand{\algorithmicelse}{\textsc{Else}}
\renewcommand{\algorithmicelsif}{\textsc{Else if}}
\renewcommand{\algorithmicrepeat}{\textsc{Do}}
\renewcommand{\algorithmicuntil}{\textsc{While}}
\renewcommand{\algorithmicdo}{\textsc{do}}
\renewcommand{\algorithmicthen}{\textsc{then}}
\renewcommand{\algorithmicwhile}{\textsc{While}}
\renewcommand{\algorithmicfor}{\textsc{For}}
\renewcommand{\algorithmicend}{\textsc{End}}
\renewcommand{\algorithmicand}{\textsc{and}}
\renewcommand{\algorithmicor}{\textsc{or}}
\renewcommand{\algorithmicxor}{\textsc{xor}}
\renewcommand{\algorithmicnot}{\textsc{not}}
\renewcommand{\algorithmictrue}{\textsc{True}}
\renewcommand{\algorithmicfalse}{\textsc{False}}
\renewcommand{\algorithmicreturn}{\textsc{Return}}
\renewcommand{\algorithmiccomment}[1]{\texttt{\#} #1}
\renewcommand{\algorithmicto}{\textsc{to}}

