max_steps: 1000
seed: 7878

world:
  size: 12
  start:
    x: 0
    y: 0
  end:
    x: 11
    y: 11
  traps:
    type: 'random'
    dist:
      empty: 0.9
      trap: 0.1

agent:
  type: 'sarsa'
  discount: 1.0
  obey_factor: 0.9
  learning_rate: 0.5

