max_steps: 10000
seed: 7878

world:
  size: 6
  start:
    x: 0
    y: 0
  end:
    x: 5
    y: 5
  traps:
    type: 'random'
    dist:
      empty: 0.8
      trap: 0.2

agent:
  type: 'q'
  discount: 0.9
  obey_factor: 0.9
  learning_rate: 0.5